update rust version, optimize build image time

diff --git a/build/Dockerfile.alpine b/build/Dockerfile.alpine
--- a/build/Dockerfile.alpine
+++ b/build/Dockerfile.alpine
@@ -1,4 +1,4 @@
-FROM golang:1.18.8-alpine
+FROM golang:1.20.10-alpine
 
 ENV RUSTUP_HOME=/usr/local/rustup \
     CARGO_HOME=/usr/local/cargo \
@@ -9,7 +9,7 @@ RUN set -eux \
 
 RUN wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rustup-init"; \
     chmod +x rustup-init; \
-    ./rustup-init -y --no-modify-path --default-toolchain 1.60.0; \
+    ./rustup-init -y --no-modify-path --default-toolchain 1.73.0; \
     rm rustup-init; \
     chmod -R a+w $RUSTUP_HOME $CARGO_HOME;
 
@@ -17,28 +17,21 @@ RUN wget "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-musl/rus
 RUN mkdir -p /.cache/go-build
 RUN chmod -R 777 /.cache
 
-# pre-fetch many deps
-WORKDIR /scratch
-COPY go-owasm /scratch/go-owasm
-RUN cd go-owasm/libgo_owasm && cargo fetch
-
 # allow non-root user to download more deps later
 RUN chmod -R 777 /usr/local/cargo
 
 # cleanup
 WORKDIR /code
-RUN rm -rf /scratch
 
 # add musl Rust targets
 RUN rustup target add x86_64-unknown-linux-musl
 
 # copy build scripts
-COPY go-owasm/build/build_alpine.sh /opt
-RUN chmod +x /opt/build*
+COPY build/*.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/*.sh
 
-# add config cargo
 RUN mkdir /.cargo
 RUN chmod +rx /.cargo
-COPY go-owasm/build/cargo-config /.cargo/config
+COPY build/cargo-config /.cargo/config
 
-CMD ["/opt/build_alpine.sh"]
+CMD ["bash", "-c", "echo 'Argument missing. Pass one build script (e.g. build_alpine.sh) to docker run' && exit 1"]
diff --git a/build/Dockerfile.linux b/build/Dockerfile.linux
--- a/build/Dockerfile.linux
+++ b/build/Dockerfile.linux
@@ -11,32 +11,25 @@ ENV RUSTUP_HOME=/usr/local/rustup \
 RUN url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; \
     wget "$url"; \
     chmod +x rustup-init; \
-    ./rustup-init -y --no-modify-path --default-toolchain 1.60.0; \
+    ./rustup-init -y --no-modify-path --default-toolchain 1.73.0; \
     rm rustup-init; \
     chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
     rustup --version; \
     cargo --version; \
     rustc --version;
 
-# pre-fetch many deps
-WORKDIR /scratch
-COPY go-owasm /scratch/go-owasm
-RUN cd go-owasm/libgo_owasm && cargo fetch
-
 # allow non-root user to download more deps later
 RUN chmod -R 777 /usr/local/cargo
 
-# cleanup
+# setup workdir
 WORKDIR /code
-RUN rm -rf /scratch
 
 # copy build scripts
-COPY go-owasm/build/build_linux.sh /opt
-RUN chmod +x /opt/build*
+COPY build/*.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/*.sh
 
-# add config cargo
 RUN mkdir /.cargo
 RUN chmod +rx /.cargo
-COPY go-owasm/build/cargo-config /.cargo/config
+COPY build/cargo-config /.cargo/config
 
-CMD ["/opt/build_linux.sh"]
+CMD ["bash", "-c", "echo 'Argument missing. Pass one build script (e.g. build_linux.sh) to docker run' && exit 1"]
diff --git a/build/Dockerfile.osx b/build/Dockerfile.osx
--- a/build/Dockerfile.osx
+++ b/build/Dockerfile.osx
@@ -1,4 +1,4 @@
-FROM rust:1.60.0-bullseye
+FROM rust:1.73.0-bullseye
 
 ENV PATH=/opt/osxcross/target/bin:$PATH
 
@@ -30,26 +30,20 @@ RUN chmod -R +rx /opt/osxcross/target/bin
 RUN /opt/osxcross/target/bin/x86_64-apple-darwin20.4-clang --version
 RUN /opt/osxcross/target/bin/aarch64-apple-darwin20.4-clang --version
 
-# pre-fetch many deps
-WORKDIR /scratch
-COPY go-owasm /scratch/go-owasm
-RUN cd go-owasm/libgo_owasm && cargo fetch
-
 # allow non-root user to download more deps later
 RUN chmod -R 777 /usr/local/cargo
 RUN chmod -R 777 /usr/local/rustup
 
-# cleanup
+# setup workdir
 WORKDIR /code
-RUN rm -rf /scratch
 
 # copy build scripts
-COPY go-owasm/build/*.sh /opt/
-RUN chmod +x /opt/*.sh
+COPY build/*.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/*.sh
 
 # add config cargo
 RUN mkdir /.cargo
 RUN chmod +rx /.cargo
-COPY go-owasm/build/cargo-config /.cargo/config
+COPY build/cargo-config /.cargo/config
 
-CMD ["/opt/build_osx.sh"]
+CMD ["bash", "-c", "echo 'Argument missing. Pass one build script (e.g. build_osx.sh) to docker run' && exit 1"]
